config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/login'
  get 'sessions/logout'
  get 'sessions/welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  resources :enrollments
  resources :courses
  resources :users
  root 'sessions#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord

  belongs_to :user
  belongs_to :course

  validates :user_id, presence: true
  validates :course_id, presence: true

  validates_uniqueness_of :user_id, scope: :course_id

  validates :score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100,  only_integer: true }

  def course_name
    Course.find(course_id).name
  end

    def user_name
    User.find(user_id).name
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]


  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = current_user.teacher? ? Enrollment.all : Enrollment.where(user_id: current_user.id)
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    @course_name = @enrollment.course_name
    @user_name = @enrollment.user_name
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    user = User.find(enrollment_params[:user_id].to_i)
    course = Course.find(enrollment_params[:course_id].to_i)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:user_id, :course_id, :score)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment, local: true) do |form| %>
  <% if enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% enrollment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.label :user_id %>
    <%= form.select :user_id, options_for_select(User.all.collect { | user | [user.name, user.id] }, current_user.id), {}, {} %>

  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.select :course_id, options_for_select(Course.all.collect { | course | [course.name, course.id] }, nil), {}, {} %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<% if current_user.teacher? %>
  <h3>You are an Admin on this system.</h3>
<% end %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Course</th>
      <th>score</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.user_name %></td>
        <td><%= enrollment.course_name %></td>
        <td><%= enrollment.score %></td>
        <td><%= link_to 'Show', enrollment %></td>

        <% if current_user.teacher? %>
          <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
          <td><%= link_to 'Un-enroll', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %> |
<%= link_to 'Users', users_path %> |
<%= link_to 'Courses', courses_path %> |
<%= link_to 'Home', '/sessions/welcome' %> |
<%= link_to 'Log Out', '/sessions/logout' %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= render 'form', enrollment: @enrollment %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @course_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @enrollment.score %>
</p>

<% if current_user.teacher? && @enrollment %>
  <%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<% end %>
<%= link_to 'Back', enrollments_path %> |
<%= link_to 'Courses', courses_path %> |
<%= link_to 'Users', users_path %> |
<%= link_to 'Home', '/sessions/welcome' %> |
<%= link_to 'Log Out', '/sessions/logout' %>